### ISSUE TITLE
Series and chapters ending with one or more periods missing downloaded content

### ISSUE THREAD

**Issue by RachaelRaysCookbook** [vignedev/dynasty-dl#10]
When downloading a series or chapter with a name ending with on or more periods(.), the download presents as successful within the CLI and a folder is created. However, when trying to open the folder (or even remove it), Windows returns an error stating the location is not available. 

Edit: As a note to anyone struggling with updating these folders, you can correct the folder name by using 7-Zip. Navigate to the parent directory, right-click on the folder, Rename (or F2), remove any (.)s. After doing so, the folder and images can be accessed/managed.

**Comment by vignedev** [comment]
Hey there, sorry it took a while for me to get here.

Apparently, that's a Windows-specific issue, as it does not appear on Linux (and I hope it does not on Mac OS or any other platforms). For a safety measure, I have added the removal of trailing periods to hopefully prevent this in the future.
